### ISSUE TITLE
auto_LiRPA runtime error for self-built onnx network

### ISSUE THREAD

**Issue by JacksonZyy** [Verified-Intelligence/alpha-beta-CROWN#16]
Hi,

I tried to run abcrown on the network built by myself.
A special thing about my network is that it is like "residual linear", where I have a "
Add" node but its inputs are two "Gemm" nodes (unlike residual block which is two Conv nodes as inputs of "Add")
The input of the network is [1, 1, 28, 28] , and I set the input shape in .yaml as well.
```
model:
   input_shape: [1, 1, 28, 28] 
```
But during execution, it gave me:
```
  File "alpha-beta-CROWN/complete_verifier/auto_LiRPA/bound_general.py", line 857, in check_prior_bounds
    node.inputs[i], prior_checked=True)
  File "alpha-beta-CROWN/complete_verifier/auto_LiRPA/bound_general.py", line 946, in compute_intermediate_bounds
    ref_intermediate_lb, ref_intermediate_ub)
  File "alpha-beta-CROWN/complete_verifier/auto_LiRPA/backward_bound.py", line 346, in get_sparse_C
    num_channel = node.output_shape[-3]
IndexError: tuple index out of range
```
I thought auto-LiRPA can handle any DAG? I am not sure what leads to the problem. 
Could you please kindly give me some advice? 

Thanks and regards,
Yuyi

**Comment by LIJYann** [comment]
I got a different problem with adding two linear layers. It seems that when it deal with the bound of an Add node, it will by default propagate a conv-like patch bound using add_bound function to its preceding node even the preceding node is linear...

**Comment by LIJYann** [comment]
I've read the code and i found that for now the get_sparse_C function only support BoundAdd with patches mode(in backward_bound.py) and I believe that might be the cause.

**Comment by KaidiXu** [comment]
@JacksonZyy Could you please post your model def so that I can reproduce the error. Thank you!

**Comment by JacksonZyy** [comment]
Hi, 

Please find the network in [https://jacksonzyy.github.io/homepage/files/red_5_100_14_003.onnx](url).
The config is given as followed:
```
model:
  onnx_path: alpha-beta-CROWN/complete_verifier/red_5_100_14_003.onnx
  input_shape: [1, 1, 28, 28]  # The vnnlib does not have input shape information, user should specify here.
specification:
  # VNNLIB file specification.
  vnnlib_path: alpha-beta-CROWN/complete_verifier/vnncomp2021/benchmarks/mnistfc/prop_14_0.03.vnnlib
solver:
  batch_size: 500
  beta-crown:
    iteration: 20
    lr_beta: 0.03
bab:
  timeout: 360
  branching:
    candidates: 5
    reduceop: max
attack:
  pgd_order: skip
```
Thanks for your help!
