### ISSUE TITLE
About the output when running on a ResNet18 pretrained model

### ISSUE THREAD

**Issue by akshaykulkarni07** [Verified-Intelligence/alpha-beta-CROWN#17]
Hi, thanks for your great work in this field. I was trying to use the `abcrown.py` file with a ResNet18 adversarially pretrained model (from the Fast Adversarial Training repo). But I'm seeing intermediate outputs like 

```
Result: unknown in 121.7578 seconds
```

Is this concerning or should I let it run completely before checking the results? Because it is taking quite some time (reached 800 out of 1000 samples on CIFAR10 in ~20 hours). Also, I had to change the config file to use 

```
  crown:
    batch_size: 8
    max_crown_size: 8
```

because the default batch size and max crown size were 10^8 which caused an out-of-memory error even on a 24GB GPU. Does that seem reasonable or will there be a problem with the evaluation (like not being comparable to the reported results in your papers)?

**Comment by huanzhang12** [comment]
Could you please give us the model, configuration file, command, and log files so we can provide more help? Thanks.

**Comment by akshaykulkarni07** [comment]
```
# This is an example configuration file that contains most useful parameter settings.
model:
  name: partial(ResNet18, in_planes=64)
  path: checkpoints/GAT_CIFAR10_ResNet18.pkl
data:
  dataset: CIFAR
  mean: [0.0, 0.0, 0.0]  # Mean for normalization.
  std: [1.0, 1.0, 1.0]  # Std for normalization.
  start: 0  # First example to verify in dataset.
  end: 1000  # Last example to verify in dataset.
specification:
  norm: .inf  # Linf norm (can also be 2 or 1).
  epsilon: 0.00784313725490196  # epsilon=2./255.
attack:  # Currently attack is only implemented for Linf norm.
  pgd_steps: 100  # Increase for a stronger attack. A PGD attack will be used before verification to filter on non-robust data examples.
  pgd_restarts: 30  # Increase for a stronger attack.
solver:
  batch_size: 8  # Number of subdomains to compute in parallel in bound solver. Decrease if you run out of memory.
  crown:
    batch_size: 8
    max_crown_size: 8
  alpha-crown:
    iteration: 100   # Number of iterations for alpha-CROWN optimization. Alpha-CROWN is used to compute all intermediate layer bounds before branch and bound starts.
    lr_alpha: 0.1    # Learning rate for alpha in alpha-CROWN. The default (0.1) is typically ok.
  beta-crown:
    lr_alpha: 0.01  # Learning rate for optimizing the alpha parameters, the default (0.01) is typically ok, but you can try to tune this parameter to get better lower bound.
    lr_beta: 0.05  # Learning rate for optimizing the beta parameters, the default (0.05) is typically ok, but you can try to tune this parameter to get better lower bound.
    iteration: 20  # Number of iterations for beta-CROWN optimization. 20 is often sufficient, 50 or 100 can also be used.
bab:
  timeout: 120  # Timeout threshold for branch and bound. Increase for verifying more points.
  branching:  # Parameters for branching heuristics.
    reduceop: min  # Reduction function for the branching heuristic scores, min or max. Using max can be better on some models.
    method: kfsb  # babsr is fast but less accurate; fsb is slow but most accurate; kfsb is usually a balance.
    candidates: 3  # Number of candidates to consider in fsb and kfsb. More leads to slower but better branching. 3 is typically good enough.
```

This is the configuration file. The model is the standard ResNet18 and the pretrained checkpoint is from [here](https://drive.google.com/drive/folders/17t2lgpMIuWztDeCCcFD_37Nj0VNpTgXh?usp=sharing). Then the command I run is `python abcrown.py --config cifar_resnet_GAT.yaml` where `cifar_resnet_GAT.yaml` contains the above provided config.

As for the logs, I have the terminal output saved to a text file but it's very very long (like 2.8 million lines when evaluating on 1000 samples of CIFAR10), so it would be helpful if you could point to any specific output you want to see. Generally, I'm seeing this 
```
Result: unknown in 121.7578 seconds
```
after every sample gets processed.
